@startuml
scale 750 width
set separator ::

namespace traffic_anal <<Rectangle>> {

	class Requests {
		+string get_segment_data(lat : double, lon : double)
		+FlowSegmentData parse_segment_data(json_str : string)
	}

	class FlowSegmentData <<struct>> {
		+frc : string
		+currentSpeed : uint
		+freeFlowSpeed : uint
		+currentTravelTime : uint
		+freeFlowTravelTime : uint
		+confidence : float
		+roadClosure : bool
	}

	class AnalyseStrategy {
		+analyse(lat : double, lon : double) : FlowSegmentData
	}

	class Analyser {
		+get_data() : FlowSegmentData

		+Analyser(lat : double, lon : double, strat : AnalyseStrategy)

		-lon : double
		-lat : double
		-strat : AnalyseStrategy
	}

	class TimePeriodData {
		+start_time : std::chrono::time_point {property}
		+end_time : std::chrono::time_point {property}
		+data : FlowSegmentData {property}
	}
}

traffic_anal::Requests --> traffic_anal::FlowSegmentData
traffic_anal::Analyser --> traffic_anal::AnalyseStrategy

@enduml
