@startuml
scale 750 width
set separator ::

namespace traffic_anal <<Rectangle>> {}

class traffic_anal::requests <<namespace>> {
    +FlowSegmentData getSegmentData(lat : double, lon : double)
    +FlowSegmentData parseSegmentData(json_str : string)
}

class traffic_anal::FlowSegmentData <<struct>> {
    +frc : string
    +currentSpeed : uint
    +freeFlowSpeed : uint
    +currentTravelTime : uint
    +freeFlowTravelTime : uint
    +confidence : float
    +roadClosure : bool
    +coordinates : vector<Coord>
}

traffic_anal::requests --> traffic_anal::FlowSegmentData

@enduml