@startuml
scale 750 width
set separator ::

namespace traffic_anal {

	class Datetime <<struct>> {
		+date : string
		+time : string
		+millis : double
	}

	class FlowSegmentData <<struct>> {
		+frc : string
		+currentSpeed : uint
		+freeFlowSpeed : uint
		+currentTravelTime : uint
		+freeFlowTravelTime : uint
		+confidence : float
		+roadClosure : bool
		+datetime : Datetime
	}

	class Dataset {
		-path : string
		-prefix : string
		-suffix : string
		-data : vector<FlowSegmentData>

		+Dataset(path string, prefix string, suffix string)

		+getData() : vector<FlowSegmentData>
		+getDataJson() : vector<json::value>
		+gatherData() : void
	}

	abstract class Analyser {
		-start : timepoint
		-end : timepoint
		-dataset : Dataset

		+analyse(start : timepoint, end : timepoint, dataset : Dataset) : FlowSegmentData {abstract}

		#Analyser()
	}
}

traffic_anal::Analyser <-- traffic_anal::FlowSegmentData
traffic_anal::Analyser <-- traffic_anal::Dataset
traffic_anal::FlowSegmentData <- traffic_anal::Datetime

@enduml
